//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neolog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neolog.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neolog.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не сте написали коментар..
        /// </summary>
        public static string comment_Empty {
            get {
                return ResourceManager.GetString("comment_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментари.
        /// </summary>
        public static string comments {
            get {
                return ResourceManager.GetString("comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запази лични данни.
        /// </summary>
        public static string conf_PrivateData {
            get {
                return ResourceManager.GetString("conf_PrivateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматично синхронизирай думите.
        /// </summary>
        public static string conf_WordSync {
            get {
                return ResourceManager.GetString("conf_WordSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В момента няма интернет връзка. Опитайте по-късно пак..
        /// </summary>
        public static string error_NoInternet {
            get {
                return ResourceManager.GetString("error_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зареждане....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За Neolog.
        /// </summary>
        public static string menu_About {
            get {
                return ResourceManager.GetString("menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Букви.
        /// </summary>
        public static string menu_Letters {
            get {
                return ResourceManager.GetString("menu_Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гнезда.
        /// </summary>
        public static string menu_Nests {
            get {
                return ResourceManager.GetString("menu_Nests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпрати дума.
        /// </summary>
        public static string menu_Post {
            get {
                return ResourceManager.GetString("menu_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпрати.
        /// </summary>
        public static string menu_Send {
            get {
                return ResourceManager.GetString("menu_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string menu_Settings {
            get {
                return ResourceManager.GetString("menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Думи.
        /// </summary>
        public static string menu_Words {
            get {
                return ResourceManager.GetString("menu_Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Има нещо изпуснато....
        /// </summary>
        public static string missingFields {
            get {
                return ResourceManager.GetString("missingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Януари.
        /// </summary>
        public static string monthFull_1 {
            get {
                return ResourceManager.GetString("monthFull_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Октомври.
        /// </summary>
        public static string monthFull_10 {
            get {
                return ResourceManager.GetString("monthFull_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ноември.
        /// </summary>
        public static string monthFull_11 {
            get {
                return ResourceManager.GetString("monthFull_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Декември.
        /// </summary>
        public static string monthFull_12 {
            get {
                return ResourceManager.GetString("monthFull_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Февруари.
        /// </summary>
        public static string monthFull_2 {
            get {
                return ResourceManager.GetString("monthFull_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Март.
        /// </summary>
        public static string monthFull_3 {
            get {
                return ResourceManager.GetString("monthFull_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Април.
        /// </summary>
        public static string monthFull_4 {
            get {
                return ResourceManager.GetString("monthFull_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Май.
        /// </summary>
        public static string monthFull_5 {
            get {
                return ResourceManager.GetString("monthFull_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юни.
        /// </summary>
        public static string monthFull_6 {
            get {
                return ResourceManager.GetString("monthFull_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юли.
        /// </summary>
        public static string monthFull_7 {
            get {
                return ResourceManager.GetString("monthFull_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Август.
        /// </summary>
        public static string monthFull_8 {
            get {
                return ResourceManager.GetString("monthFull_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Септември.
        /// </summary>
        public static string monthFull_9 {
            get {
                return ResourceManager.GetString("monthFull_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Затвори.
        /// </summary>
        public static string popup_Cancel {
            get {
                return ResourceManager.GetString("popup_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОК.
        /// </summary>
        public static string popup_OK {
            get {
                return ResourceManager.GetString("popup_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какво значи:.
        /// </summary>
        public static string send_Description {
            get {
                return ResourceManager.GetString("send_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string send_Email {
            get {
                return ResourceManager.GetString("send_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Етимология (произход):.
        /// </summary>
        public static string send_Ethimology {
            get {
                return ResourceManager.GetString("send_Ethimology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примери:.
        /// </summary>
        public static string send_Example {
            get {
                return ResourceManager.GetString("send_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име/псевдоним:.
        /// </summary>
        public static string send_Name {
            get {
                return ResourceManager.GetString("send_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гнездо:.
        /// </summary>
        public static string send_Nest {
            get {
                return ResourceManager.GetString("send_Nest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашият сайт:.
        /// </summary>
        public static string send_URL {
            get {
                return ResourceManager.GetString("send_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Думата:.
        /// </summary>
        public static string send_Word {
            get {
                return ResourceManager.GetString("send_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментирай.
        /// </summary>
        public static string sendComment {
            get {
                return ResourceManager.GetString("sendComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпрати на email....
        /// </summary>
        public static string share_Email_Desc {
            get {
                return ResourceManager.GetString("share_Email_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Благодарим ви!.
        /// </summary>
        public static string thankYou {
            get {
                return ResourceManager.GetString("thankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Понеделник.
        /// </summary>
        public static string weekday_1 {
            get {
                return ResourceManager.GetString("weekday_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вторник.
        /// </summary>
        public static string weekday_2 {
            get {
                return ResourceManager.GetString("weekday_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сряда.
        /// </summary>
        public static string weekday_3 {
            get {
                return ResourceManager.GetString("weekday_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Четвъртък.
        /// </summary>
        public static string weekday_4 {
            get {
                return ResourceManager.GetString("weekday_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Петък.
        /// </summary>
        public static string weekday_5 {
            get {
                return ResourceManager.GetString("weekday_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Събота.
        /// </summary>
        public static string weekday_6 {
            get {
                return ResourceManager.GetString("weekday_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неделя.
        /// </summary>
        public static string weekday_7 {
            get {
                return ResourceManager.GetString("weekday_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Етимология.
        /// </summary>
        public static string word_Ethimology {
            get {
                return ResourceManager.GetString("word_Ethimology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примери.
        /// </summary>
        public static string word_Example {
            get {
                return ResourceManager.GetString("word_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Твоят коментар:.
        /// </summary>
        public static string your_Comment {
            get {
                return ResourceManager.GetString("your_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име/псевдоним:.
        /// </summary>
        public static string your_CommentAuhor {
            get {
                return ResourceManager.GetString("your_CommentAuhor", resourceCulture);
            }
        }
    }
}
