//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neolog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neolog.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neolog.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t enter comment..
        /// </summary>
        public static string comment_Empty {
            get {
                return ResourceManager.GetString("comment_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string comments {
            get {
                return ResourceManager.GetString("comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save private data.
        /// </summary>
        public static string conf_PrivateData {
            get {
                return ResourceManager.GetString("conf_PrivateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize words automatically.
        /// </summary>
        public static string conf_WordSync {
            get {
                return ResourceManager.GetString("conf_WordSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet connection at the moment. Please, try again later..
        /// </summary>
        public static string error_NoInternet {
            get {
                return ResourceManager.GetString("error_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured. Please, try again later..
        /// </summary>
        public static string generalError {
            get {
                return ResourceManager.GetString("generalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Neolog.
        /// </summary>
        public static string menu_About {
            get {
                return ResourceManager.GetString("menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letters.
        /// </summary>
        public static string menu_Letters {
            get {
                return ResourceManager.GetString("menu_Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nests.
        /// </summary>
        public static string menu_Nests {
            get {
                return ResourceManager.GetString("menu_Nests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a word.
        /// </summary>
        public static string menu_Post {
            get {
                return ResourceManager.GetString("menu_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string menu_Send {
            get {
                return ResourceManager.GetString("menu_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string menu_Settings {
            get {
                return ResourceManager.GetString("menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words.
        /// </summary>
        public static string menu_Words {
            get {
                return ResourceManager.GetString("menu_Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something is missing....
        /// </summary>
        public static string missingFields {
            get {
                return ResourceManager.GetString("missingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string monthFull_1 {
            get {
                return ResourceManager.GetString("monthFull_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string monthFull_10 {
            get {
                return ResourceManager.GetString("monthFull_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string monthFull_11 {
            get {
                return ResourceManager.GetString("monthFull_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string monthFull_12 {
            get {
                return ResourceManager.GetString("monthFull_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string monthFull_2 {
            get {
                return ResourceManager.GetString("monthFull_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string monthFull_3 {
            get {
                return ResourceManager.GetString("monthFull_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string monthFull_4 {
            get {
                return ResourceManager.GetString("monthFull_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string monthFull_5 {
            get {
                return ResourceManager.GetString("monthFull_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string monthFull_6 {
            get {
                return ResourceManager.GetString("monthFull_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string monthFull_7 {
            get {
                return ResourceManager.GetString("monthFull_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string monthFull_8 {
            get {
                return ResourceManager.GetString("monthFull_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string monthFull_9 {
            get {
                return ResourceManager.GetString("monthFull_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string popup_Cancel {
            get {
                return ResourceManager.GetString("popup_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string popup_OK {
            get {
                return ResourceManager.GetString("popup_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meaning:.
        /// </summary>
        public static string send_Description {
            get {
                return ResourceManager.GetString("send_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string send_Email {
            get {
                return ResourceManager.GetString("send_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethimology (origin):.
        /// </summary>
        public static string send_Ethimology {
            get {
                return ResourceManager.GetString("send_Ethimology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples:.
        /// </summary>
        public static string send_Example {
            get {
                return ResourceManager.GetString("send_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name/nickname:.
        /// </summary>
        public static string send_Name {
            get {
                return ResourceManager.GetString("send_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nest:.
        /// </summary>
        public static string send_Nest {
            get {
                return ResourceManager.GetString("send_Nest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your web-site:.
        /// </summary>
        public static string send_URL {
            get {
                return ResourceManager.GetString("send_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word:.
        /// </summary>
        public static string send_Word {
            get {
                return ResourceManager.GetString("send_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string sendComment {
            get {
                return ResourceManager.GetString("sendComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to email....
        /// </summary>
        public static string share_Email_Desc {
            get {
                return ResourceManager.GetString("share_Email_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You!.
        /// </summary>
        public static string thankYou {
            get {
                return ResourceManager.GetString("thankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The author URL is not correctly formatted..
        /// </summary>
        public static string urlError {
            get {
                return ResourceManager.GetString("urlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string weekday_1 {
            get {
                return ResourceManager.GetString("weekday_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string weekday_2 {
            get {
                return ResourceManager.GetString("weekday_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string weekday_3 {
            get {
                return ResourceManager.GetString("weekday_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string weekday_4 {
            get {
                return ResourceManager.GetString("weekday_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string weekday_5 {
            get {
                return ResourceManager.GetString("weekday_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string weekday_6 {
            get {
                return ResourceManager.GetString("weekday_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string weekday_7 {
            get {
                return ResourceManager.GetString("weekday_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethimology.
        /// </summary>
        public static string word_Ethimology {
            get {
                return ResourceManager.GetString("word_Ethimology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string word_Example {
            get {
                return ResourceManager.GetString("word_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your comment:.
        /// </summary>
        public static string your_Comment {
            get {
                return ResourceManager.GetString("your_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name/nickname: .
        /// </summary>
        public static string your_CommentAuhor {
            get {
                return ResourceManager.GetString("your_CommentAuhor", resourceCulture);
            }
        }
    }
}
